apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: sarahzemo/karsajobs-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VUE_APP_BACKEND
              value: http://localhost:8080
          ports:
            - containerPort: 80